services:
  frontend:
    build:
      context: frontend
      args:
        REACT_APP_HOST_IP_ADDRESS: http://127.0.0.1:80
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}:/frontend/app
      - /frontend/app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: backend
    ports:
      - "80:80"
    environment: 
      - MAX_WORKERS=1
volumes:
  logvolume01: {}
