name: Validate format and tests 

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install requirements and run pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -t .
          python3 -m pytest backend/app/test --verbose
